### ISSUE TITLE
Feature 1: User can view a list of body parts / exercise categories. 

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/ajax-project#1]
## 📐 Plan

Create a responsive list that allows users to view 

## 🖼️ Wireframes

![Screen Shot 2022-06-13 at 2 57 47 PM](https://user-images.githubusercontent.com/103611252/173452168-8ca0d3ab-2c67-4e2f-9d63-c47b2ff48575.png)
![Screen Shot 2022-06-13 at 2 58 09 PM](https://user-images.githubusercontent.com/103611252/173452205-9f81231f-13ec-4da2-8e39-438cd453c58a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Complete HTML layout and background design 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Make sure button has an active effect and a hover effect. 
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
  - [ ]  Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [ ] Test all functionality again in a private browsing session.
  - [ ] Fix all errors.
