### ISSUE TITLE
Feature 1: User can search for a food item. 

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/ajax-project#1]
## ⚙️ Feature

> ##### Users can search for a food item. 

## 📐 Functionality

> ##### User can input text into the search bar. After pressing the button to the right of the search bar, data will generate consisting of food selection.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) 

![Screen Shot 2022-08-01 at 11 06 30 AM](https://user-images.githubusercontent.com/103611252/182213360-b3a2d359-aba2-4e7c-b3da-97c14482e924.png)
![Screen Shot 2022-08-01 at 11 06 55 AM](https://user-images.githubusercontent.com/103611252/182213421-49afa80d-2303-4cc5-824f-aa1de489d402.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="home-page"]` to the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Create a dummy ul list to match searched food items.
- [x] Listen for `'input'` events on the `search` input to update the `class` attribute of the other div elements.
- [x] Listen for `'submit'` events on the search bar and load the data from the Nutrionix API by:
     - [x] creating a new XMLHttpRequest object
     - [x] open the xhr object to send a 'GET' request
     - [x] set the responseType
     - [x] listen for the 'load' event on the xhr object in order to
     - [x] loop through the response of the xhr object.
     - [x] for each user object in the response, create a li element and append it to the 'ul' element
     - [x] send() the request to begin loading the data from the server.
- [x] Listen for 'click' events on the application name which will redirect the user back to main by hiding the div[data-view="search-page"]
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
